# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVmJgOo46QFAca5eu6lcsMleFXFcGANv
"""

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

# Load data and model - relative paths from dashboards/ to root folders
data_path = '../data/processed/processed_data.csv'
model_path = '../models/failure_model.pkl'
try:
    df = pd.read_csv(data_path)
    model = joblib.load(model_path)
except FileNotFoundError:
    st.error("File not found! Check paths to processed_data.csv and failure_model.pkl")
    st.stop()

# Title and intro
st.title('IoT Predictive Maintenance Dashboard')
st.write('Baseline dashboard for industrial machine failure prediction using AI4I data.')

# Section 1: Data Summary
st.subheader('Data Overview')
st.write('Processed dataset summary (first 10 rows, shape, stats):')
st.dataframe(df.head(10))
st.write(f'Shape: {df.shape}')
st.dataframe(df.describe())

# Section 2: Interactive Plots
st.subheader('Interactive Plot: Torque vs Failure by Machine Type')
st.write('Filter by Type (encoded: 0=L, 1=M, 2=H) to see patterns.')
type_filter = st.selectbox('Select Machine Type:', ['All', 'L (0)', 'M (1)', 'H (2)'])

# Filter df
if type_filter != 'All':
    type_map = {'L (0)': 0, 'M (1)': 1, 'H (2)': 2}
    filtered_df = df[df['Type'] == type_map[type_filter]]
else:
    filtered_df = df

# Boxplot
fig, ax = plt.subplots(figsize=(8, 6))
sns.boxplot(x='Machine failure', y='Torque [Nm]', data=filtered_df, ax=ax)
ax.set_title(f'Torque vs Failure (Filtered: {type_filter})')
st.pyplot(fig)

# Section 3: Model Predictions
st.subheader('Predict Failure')
st.write('Slide normalized values (0-1) for sensors. High torque/wear often triggers failure.')
type_val = st.slider('Type (0=L, 1=M, 2=H)', 0.0, 2.0, 1.0, step=1.0)
air_temp = st.slider('Air Temperature [K]', 0.0, 1.0, 0.5)
proc_temp = st.slider('Process Temperature [K]', 0.0, 1.0, 0.5)
rpm = st.slider('Rotational Speed [rpm]', 0.0, 1.0, 0.5)
torque = st.slider('Torque [Nm]', 0.0, 1.0, 0.5)
tool_wear = st.slider('Tool Wear [min]', 0.0, 1.0, 0.5)

# Input DataFrame
input_df = pd.DataFrame({
    'Type': [type_val],
    'Air temperature [K]': [air_temp],
    'Process temperature [K]': [proc_temp],
    'Rotational speed [rpm]': [rpm],
    'Torque [Nm]': [torque],
    'Tool wear [min]': [tool_wear]
})

if st.button('Predict'):
    pred = model.predict(input_df)[0]
    prob = model.predict_proba(input_df)[0][1]
    result = 'Failure Detected!' if pred == 1 else 'No Failure'
    st.success(f'{result} (Failure Probability: {prob:.2%})')

# Footer
st.markdown('---')
st.write('For IoT DS Project – local run fixed.')
